"""initial schema

Revision ID: d6e8c2e05497
Revises:
Create Date: 2026-03-19 10:52:44.775586

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d6e8c2e05497"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agencies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("location", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agencies_code"), "agencies", ["code"], unique=True)
    op.create_table(
        "audit_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("table_name", sa.String(length=100), nullable=True),
        sa.Column("record_id", sa.String(length=100), nullable=True),
        sa.Column("old_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("new_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("performed_by", sa.UUID(), nullable=True),
        sa.Column("performed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("client_ip", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("request_id", sa.UUID(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_log_performed_at"), "audit_log", ["performed_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_log_performed_by"), "audit_log", ["performed_by"], unique=False
    )
    op.create_table(
        "otp_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("code_hash", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=True),
        sa.Column("is_used", sa.Boolean(), nullable=True),
        sa.Column("request_ip", postgresql.INET(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pep_sanctions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("aliases", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("date_of_birth", sa.DATE(), nullable=True),
        sa.Column("nationality", sa.String(length=100), nullable=True),
        sa.Column("programs", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("last_synced_at", sa.DATE(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pep_sanctions_full_name"), "pep_sanctions", ["full_name"], unique=False
    )
    op.create_table(
        "provisioning_batches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_items", sa.Integer(), nullable=True),
        sa.Column("success_count", sa.Integer(), nullable=True),
        sa.Column("error_count", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("pin_hash", sa.String(length=255), nullable=True),
        sa.Column("biometric_opt_in", sa.Boolean(), nullable=True),
        sa.Column("language", sa.String(length=10), nullable=True),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("liveness_lockout_count_24h", sa.Integer(), nullable=True),
        sa.Column("last_lockout_reset_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_phone"), "users", ["phone"], unique=True)
    op.create_table(
        "agents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("agency_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("static_weight", sa.Integer(), nullable=True),
        sa.Column("current_weight", sa.Integer(), nullable=True),
        sa.Column("is_available", sa.Boolean(), nullable=True),
        sa.Column("active_dossier_count", sa.Integer(), nullable=True),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["agency_id"],
            ["agencies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agents_email"), "agents", ["email"], unique=True)
    op.create_table(
        "kyc_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("agency_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("access_level", sa.String(length=50), nullable=False),
        sa.Column("niu_type", sa.String(length=50), nullable=True),
        sa.Column(
            "confidence_score_global", sa.Numeric(precision=5, scale=4), nullable=True
        ),
        sa.Column("liveness_strike_count", sa.Integer(), nullable=True),
        sa.Column("priority_flag", sa.Boolean(), nullable=True),
        sa.Column("doc_expiry_flag", sa.Boolean(), nullable=True),
        sa.Column("doc_expiry_deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("doc_expiry_notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("escalated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_step_completed", sa.String(length=100), nullable=True),
        sa.Column("submission_ip", postgresql.INET(), nullable=True),
        sa.ForeignKeyConstraint(
            ["agency_id"],
            ["agencies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "aml_alerts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("pep_sanctions_id", sa.UUID(), nullable=True),
        sa.Column("alert_type", sa.String(length=50), nullable=False),
        sa.Column("match_score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("cleared_by", sa.UUID(), nullable=True),
        sa.Column("justification", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["cleared_by"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pep_sanctions_id"],
            ["pep_sanctions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["kyc_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "biometric_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("face_match_score", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("liveness_score", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column(
            "anti_spoofing_score", sa.Numeric(precision=5, scale=4), nullable=True
        ),
        sa.Column("model_version_face", sa.String(length=50), nullable=True),
        sa.Column("model_version_liveness", sa.String(length=50), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["kyc_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "consent_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("cgu_accepted", sa.Boolean(), nullable=True),
        sa.Column("privacy_accepted", sa.Boolean(), nullable=True),
        sa.Column("data_processing_accepted", sa.Boolean(), nullable=True),
        sa.Column("consent_method", sa.String(length=50), nullable=False),
        sa.Column("cgu_version", sa.String(length=20), nullable=True),
        sa.Column("privacy_version", sa.String(length=20), nullable=True),
        sa.Column(
            "consent_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("signed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("client_ip", postgresql.INET(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["kyc_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("doc_type", sa.String(length=50), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("sha256_hash", sa.String(length=64), nullable=False),
        sa.Column("ocr_engine", sa.String(length=50), nullable=True),
        sa.Column(
            "ocr_raw_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "confidence_per_field",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "capture_quality_metrics",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["kyc_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dossier_assignments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["kyc_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "duplicate_checks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id_new", sa.UUID(), nullable=False),
        sa.Column("session_id_existing", sa.UUID(), nullable=False),
        sa.Column("match_type", sa.String(length=50), nullable=False),
        sa.Column("resolution", sa.String(length=50), nullable=True),
        sa.Column("resolved_by", sa.UUID(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["resolved_by"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id_existing"],
            ["kyc_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id_new"],
            ["kyc_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "provisioning_batch_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("batch_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("axway_request_id", sa.String(length=100), nullable=True),
        sa.Column("iso20022_message_ref", sa.String(length=100), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["provisioning_batches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["kyc_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "support_threads",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["kyc_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "validation_decisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("decision", sa.String(length=50), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("agent_ip", postgresql.INET(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["kyc_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ocr_fields",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("field_name", sa.Text(), nullable=False),
        sa.Column("extracted_value", sa.Text(), nullable=True),
        sa.Column("confidence_score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("human_corrected", sa.Boolean(), nullable=True),
        sa.Column("corrected_value", sa.Text(), nullable=True),
        sa.Column("corrected_by_agent_id", sa.UUID(), nullable=True),
        sa.Column("corrected_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["corrected_by_agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "support_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("sender_type", sa.String(length=20), nullable=False),
        sa.Column("sender_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("attachment_path", sa.Text(), nullable=True),
        sa.Column("attachment_sha256", sa.String(length=64), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["support_threads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("support_messages")
    op.drop_table("ocr_fields")
    op.drop_table("validation_decisions")
    op.drop_table("support_threads")
    op.drop_table("provisioning_batch_items")
    op.drop_table("duplicate_checks")
    op.drop_table("dossier_assignments")
    op.drop_table("documents")
    op.drop_table("consent_records")
    op.drop_table("biometric_results")
    op.drop_table("aml_alerts")
    op.drop_table("notifications")
    op.drop_table("kyc_sessions")
    op.drop_index(op.f("ix_agents_email"), table_name="agents")
    op.drop_table("agents")
    op.drop_index(op.f("ix_users_phone"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("provisioning_batches")
    op.drop_index(op.f("ix_pep_sanctions_full_name"), table_name="pep_sanctions")
    op.drop_table("pep_sanctions")
    op.drop_table("otp_sessions")
    op.drop_index(op.f("ix_audit_log_performed_by"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_performed_at"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_agencies_code"), table_name="agencies")
    op.drop_table("agencies")
    # ### end Alembic commands ###
