from pathlib import Path
from shutil import copyfile

from docx import Document
from docx.oxml.ns import qn
from docx.shared import Pt


BASE = Path(__file__).resolve().parent
SRC = BASE / "memoire-stage-andre-yoann-kenmogne-v6.docx"
DST = BASE / "memoire-stage-andre-yoann-kenmogne-v7.docx"


def set_font(paragraph):
    for run in paragraph.runs:
        run.font.name = "Arial"
        run._element.rPr.rFonts.set(qn("w:ascii"), "Arial")
        run._element.rPr.rFonts.set(qn("w:hAnsi"), "Arial")
        run._element.rPr.rFonts.set(qn("w:cs"), "Arial")
        if paragraph.style.name in {"Memoire Body", "Front Matter", "Normal"}:
            run.font.size = Pt(12)


def replace_paragraph(doc, old, new):
    for p in doc.paragraphs:
        if p.text == old:
            p.clear()
            p.add_run(new)
            set_font(p)
            return True
    return False


def replace_inside(doc, old, new):
    changed = False
    for p in doc.paragraphs:
        if old in p.text:
            text = p.text.replace(old, new)
            p.clear()
            p.add_run(text)
            set_font(p)
            changed = True
    for table in doc.tables:
        for row in table.rows:
            for cell in row.cells:
                if old in cell.text:
                    cell.text = cell.text.replace(old, new)
                    changed = True
    return changed


def replace_containing(doc, needle, new):
    for p in doc.paragraphs:
        if needle in p.text:
            p.clear()
            p.add_run(new)
            set_font(p)
            return True
    return False


def scan(doc):
    parts = []
    for p in doc.paragraphs:
        parts.append(p.text)
    for table in doc.tables:
        for row in table.rows:
            for cell in row.cells:
                parts.append(cell.text)
    text = "\n".join(parts)
    bad = {
        "em_dash": "\u2014" in text,
        "en_dash": "\u2013" in text,
        "spaced_hyphen": " - " in text,
        "old_800": "800" in text,
        "fictive_Jean": "Jean" in text,
        "fictive_Thomas": "Thomas" in text,
        "fictive_Sylvie": "Sylvie" in text,
        "Admin IT": "Admin IT" in text,
        "sommaire_provisoire": "SOMMAIRE PROVISOIRE" in text,
        "vague_bicec": "D'après sa communication institutionnelle" in text,
    }
    failed = [k for k, v in bad.items() if v]
    if failed:
        raise SystemExit(f"Scan failed: {failed}")


def main():
    copyfile(SRC, DST)
    doc = Document(DST)

    replacements = {
        "Le mémoire est désormais structuré en cinq chapitres. Le premier présente le cadre institutionnel, le contexte métier, la réglementation COBAC et la problématique de recherche. Le deuxième analysera les besoins, les données KYC, les exigences fonctionnelles et le cadrage méthodologique. Le troisième sera consacré à l'architecture de traitement KYC, OCR et biométrique. Le quatrième présentera la réalisation et l'intégration des mécanismes intelligents de vérification. Le cinquième portera sur l'évaluation, la sécurité, le déploiement, l'impact et les limites. La conclusion reviendra sur les acquis techniques, organisationnels et humains du stage.": "Le mémoire est structuré en cinq chapitres. Le premier présente le cadre institutionnel, le contexte métier, la réglementation COBAC et la problématique de recherche. Le deuxième analyse les besoins, les données KYC, les exigences fonctionnelles et le cadrage méthodologique. Le troisième décrit l'architecture de traitement KYC, OCR et biométrique. Le quatrième présente la réalisation et l'intégration des mécanismes intelligents de vérification. Le cinquième traite l'évaluation, la sécurité, le déploiement, l'impact et les limites. La conclusion synthétise les acquis techniques, organisationnels et humains du stage.",
        "La Banque Internationale du Cameroun pour l'Epargne et le Crédit, plus connue sous le sigle BICEC, est une banque camerounaise opérant sur les marchés des particuliers, des professionnels et des entreprises. D'après sa communication institutionnelle, elle est filiale du Groupe Banque Centrale Populaire et figure parmi les acteurs de référence du secteur bancaire au Cameroun. La fiche de validation du sujet de stage indique un effectif d'environ 600 collaborateurs.": "La Banque Internationale du Cameroun pour l'Epargne et le Crédit, plus connue sous le sigle BICEC, est une banque camerounaise opérant sur les marchés des particuliers, des professionnels et des entreprises. La présentation institutionnelle de la banque la situe comme filiale du Groupe Banque Centrale Populaire et comme acteur de référence du paysage bancaire camerounais (BICEC, 2026). La fiche de validation du sujet de stage retient, pour le périmètre de ce mémoire, un effectif d'environ 600 collaborateurs.",
        "Le chapitre ne cherche pas encore à décrire l'architecture. Il établit le besoin avec assez de précision pour que les choix techniques du chapitre 3 puissent être évalués selon des critères métier, réglementaires et opérationnels.": "Il ne décrit pas encore l'architecture technique. Il fixe d'abord le besoin avec assez de précision pour que les choix du chapitre 3 puissent être évalués selon des critères métier, réglementaires et opérationnels.",
        "Le résultat attendu n'est donc pas une décision automatique d'entrée en relation. La solution doit préparer un dossier plus complet, mieux tracé et plus rapide à instruire, tout en laissant la validation finale aux agents habilités.": "Le résultat attendu n'est donc pas une entrée en relation décidée automatiquement. La solution doit préparer un dossier plus complet, mieux tracé et plus rapide à instruire, tout en laissant la validation finale aux agents habilités.",
        "Le système doit donc détecter les défauts le plus tôt possible, avant que le dossier ne surcharge la file de revue.": "Le système doit donc détecter les défauts dès la capture, afin d'éviter l'arrivée de dossiers difficilement exploitables dans la file de revue.",
        "L'état de l'art conduit donc à une position prudente : VeriPass ne doit pas promettre une automatisation totale. Il doit produire une preuve exploitable, réduire les erreurs répétitives, prioriser les dossiers à risque et fournir aux équipes BICEC des éléments traçables pour décider.": "L'état de l'art conduit à une position prudente : VeriPass ne doit pas promettre une automatisation totale. Son rôle est de produire une preuve exploitable, de réduire les erreurs répétitives, de prioriser les dossiers à risque et de fournir aux équipes BICEC des éléments traçables pour décider.",
        "La décision ne peut donc pas reposer sur un score isolé. Elle doit s'appuyer sur un ensemble de signaux : succès du challenge, qualité du selfie, score de matching, statut du document et possibilité de revue humaine.": "La décision ne peut pas reposer sur un score isolé. Elle doit s'appuyer sur un ensemble de signaux : succès du challenge, qualité du selfie, score de matching, statut du document et possibilité de revue humaine.",
        "La méthode s'appuie sur des livrables intermédiaires : écrans de parcours, contrats d'API, modèles de données, scénarios de test et notes de durcissement. Ils servent à aligner le responsable de stage, les équipes techniques et les attentes de conformité.": "La méthode s'appuie sur des livrables intermédiaires : écrans de parcours, contrats API, modèles de données, scénarios de test et notes de durcissement. Ces livrables alignent le responsable de stage, les équipes techniques et les attentes de conformité.",
        "Le point le plus important est la séparation des responsabilités. La capture n'est pas la décision, l'OCR n'est pas la vérité métier, le score biométrique n'est pas une validation et le stockage documentaire n'est pas un audit complet. L'architecture VeriPass assemble ces éléments pour produire un dossier exploitable par une banque.": "Le principe central de l'architecture est la séparation des responsabilités. La capture n'est pas la décision, l'OCR n'est pas la vérité métier, le score biométrique n'est pas une validation et le stockage documentaire n'est pas un audit complet. VeriPass articule ces éléments pour produire un dossier exploitable par une banque.",
        "Cette combinaison est adaptée à un projet en évolution. Les tables stables portent les responsabilités métier : dossier, document, champ, biométrie, décision et audit. Les colonnes plus flexibles absorbent les variations des moteurs OCR et biométriques. Le modèle peut ainsi évoluer sans perdre la lisibilité nécessaire à la conformité.": "Cette combinaison convient à un projet appelé à évoluer. Les tables stables portent les responsabilités métier : dossier, document, champ, biométrie, décision et audit. Les colonnes plus flexibles absorbent les variations des moteurs OCR et biométriques. Le modèle peut ainsi évoluer sans perdre la lisibilité nécessaire à la conformité.",
        "Ce chapitre sera développé dans une itération ultérieure. Il présentera la réalisation du pipeline, l'intégration FastAPI, les écrans PWA et les axes de traitement des données d'identité.": "Ce chapitre reste à développer dans la suite de la rédaction. Il présentera la réalisation du pipeline, l'intégration FastAPI, les écrans PWA et les axes de traitement des données d'identité.",
        "Ce chapitre sera développé dans une itération ultérieure. Il traitera le protocole d'évaluation, les jeux de tests, les métriques OCR et biométriques, la sécurité, la conformité, le déploiement, l'impact, les limites et les perspectives d'industrialisation.": "Ce chapitre reste à développer dans la suite de la rédaction. Il traitera le protocole d'évaluation, les jeux de tests, les métriques OCR et biométriques, la sécurité, la conformité, le déploiement, l'impact, les limites et les perspectives d'industrialisation.",
        "Les acquis organisationnels sont tout aussi importants. Le stage a placé le développement dans un environnement bancaire exigeant, où la vitesse de réalisation doit rester compatible avec la conformité, l'audit et la protection des données. Les échanges avec les équipes ont montré que la bonne solution n'est pas celle qui automatise le plus, mais celle qui aide les acteurs à décider plus vite et mieux.": "Les acquis organisationnels complètent ces acquis techniques. Le stage a placé le développement dans un environnement bancaire exigeant, où la vitesse de réalisation doit rester compatible avec la conformité, l'audit et la protection des données. Les échanges avec les équipes ont montré que la bonne solution n'est pas celle qui automatise le plus, mais celle qui aide les acteurs habilités à décider plus vite, avec davantage de preuves.",
        "Les perspectives portent sur l'industrialisation du pipeline, la certification ou validation du dispositif dans le cadre COBAC, l'extension à d'autres parcours clients et l'adaptation à d'autres banques de la zone CEMAC. VeriPass peut devenir un socle régional de RegTech bancaire, à condition de conserver son principe directeur : automatiser les contrôles répétitifs, mais garder la responsabilité humaine sur les décisions sensibles.": "Les perspectives portent sur l'industrialisation du pipeline, la certification ou la validation du dispositif dans le cadre COBAC, l'extension à d'autres parcours clients et l'adaptation à d'autres banques de la zone CEMAC. VeriPass pourrait devenir un socle régional de RegTech bancaire, à condition de conserver son principe directeur : automatiser les contrôles répétitifs, mais garder la responsabilité humaine sur les décisions sensibles.",
        "Les captures d'écran disponibles dans docs/test-evidence/latest illustrent les files back office, les alertes AML, la démonstration de conformité, les écrans mobiles de parcours KYC et les preuves d'exécution E2E. Elles doivent être insérées dans la version finale lorsque les chapitres 4 et 5 seront rédigés.": "Les captures d'écran disponibles dans docs/test-evidence/latest illustrent les files back office, les alertes AML, la démonstration de conformité, les écrans mobiles du parcours KYC et les preuves d'exécution E2E. Elles seront sélectionnées et insérées dans la version finale des chapitres 4 et 5.",
        "Le premier chapitre a établi le cadre institutionnel, réglementaire, métier, technique et économique du projet VeriPass. Le présent chapitre traduit ce cadre global en spécifications détaillées d'ingénierie logicielle. Il précise les objectifs du besoin, les rôles des différents acteurs, les flux de données, les parcours client et interne, les critères de qualité des données KYC, puis effectue une revue rigoureuse de l'état de l'art scientifique. Enfin, il formalise les exigences fonctionnelles et non fonctionnelles, détaille la méthodologie hybride agile de conduite de projet et présente le bilan de nos acquis d'apprentissage.": "Le premier chapitre a établi le cadre institutionnel, réglementaire et métier du projet VeriPass. Le présent chapitre transforme ce cadre en besoins de conception. Il précise les objectifs du périmètre, les acteurs, les parcours, les données KYC, les critères de qualité, l'état de l'art utile au projet, les exigences fonctionnelles et non fonctionnelles, puis la méthode de conduite retenue.",
        "L'objectif premier de la plateforme VeriPass est de ramener le temps total d'enrôlement client sous la barre des 15 minutes, avec un benchmark d'interaction client de 11 minutes, tout en garantissant l'intégrité absolue des contrôles réglementaires KYC. Le système doit guider l'utilisateur pas à pas, assurer la capture et la validation de ses pièces d'identité, vérifier sa vivacité biométrique en temps réel, recueillir son consentement et transmettre un dossier chiffré et immuable au back office central.": "L'objectif premier de VeriPass est de réduire le temps et l'effort de constitution d'un dossier KYC, sans affaiblir les contrôles réglementaires. Le système doit guider l'utilisateur pas à pas, collecter les pièces utiles, permettre la vérification des champs extraits, réaliser une preuve de vie, recueillir le consentement et transmettre au back office un dossier structuré, traçable et exploitable.",
        "Le périmètre fonctionnel du MVP couvre le parcours client mobile (authentification par mot de passe à usage unique OTP, capture de la CNI recto/verso, liveness challenge, saisie de l'adresse avec GPS ou facture ENEO/CAMWATER, consentement Loi n° 2024/017 et signature tactile), la file d'attente de validation des agents de conformité, et la passerelle technique vers les applications cibles de la BICEC. De façon stratégique, pour limiter l'abandon client pendant la phase de validation administrative (état RESTRICTED), l'application mobile intègre des démonstrations de fonctionnalités bancaires adaptées au statut d'accès du compte (Plan Premium/Standard, Everyday Needs, Cards management et linked accounts). Ces modules engagent l'utilisateur et intègrent un Single Sign-On (SSO) deep-link vers l'application de micro-crédit Bi-Cresco.": "Le périmètre fonctionnel du MVP couvre le parcours client mobile (authentification par OTP, capture de la CNI recto verso, preuve de vie, saisie de l'adresse, consentement et signature), la file de validation interne et le suivi du statut du dossier. Les intégrations vers les systèmes bancaires de production, l'ouverture comptable effective et l'activation commerciale complète restent hors périmètre de ce mémoire.",
        "La réalisation de ce périmètre nécessite la collaboration coordonnée de plusieurs acteurs au sein du système, définis selon des rôles et des niveaux de sécurité stricts au sein de l'organisation.": "La réalisation de ce périmètre suppose une séparation claire des rôles, car la collecte, le contrôle, la décision et l'administration ne relèvent pas des mêmes responsabilités.",
        "L'architecture fonctionnelle de VeriPass repose sur cinq rôles distincts et complémentaires, séparant strictement la collecte de données, la validation métier, la supervision nationale, la direction de la conformité et la configuration technique.": "L'architecture fonctionnelle de VeriPass repose sur des rôles complémentaires. Le client constitue le dossier, l'agent KYC ou chargé de clientèle l'instruit, l'analyste AML/CFT traite les alertes, la responsable conformité supervise les exigences de contrôle et l'administrateur IT maintient les paramètres techniques.",
        "La répartition de ces responsabilités se matérialise sur le terrain par deux parcours distincts mais intimement liés : le parcours d'acquisition client mobile-first et le parcours de validation interne centralisé.": "Cette répartition se traduit par deux parcours liés : le parcours d'acquisition client dans l'application mobile et le parcours de validation interne dans le back office.",
        "Le parcours client mobile est séquentiel et conçu pour résister aux aléas d'infrastructure (scénario 'ENEO Blackout'). En cas de coupure de réseau ou de délestage électrique, la PWA sauvegarde localement l'état d'enrôlement et les images cryptées à chaque étape via IndexedDB. Lors du rétablissement du réseau, l'application effectue un progressive upload asynchrone sécurisé, permettant au client de reprendre exactement là où il s'était arrêté en moins de 2 secondes, éliminant ainsi le risque d'abandon client lié aux instabilités locales.": "Le parcours client mobile est séquentiel. Il doit rester compréhensible même lorsque la connexion est instable ou lorsque l'utilisateur interrompt la saisie. La PWA conserve l'état d'avancement du parcours et facilite la reprise de session, afin de limiter les abandons liés aux interruptions de réseau ou aux erreurs de capture.",
        "Le parcours interne débute dès la soumission du dossier. Un algorithme de dispatching et de load-balancing intelligent attribue le dossier à une agence et à un agent disponible de cette même agence. Si le client autorise la capture GPS, le système réalise un fuzzy matching rapide par rapport aux coordonnées géographiques des agences BICEC stockées. En cas de refus du GPS, le système extrait le quartier de facturation de l'électricité (ENEO) ou de l'eau (CAMWATER) présente sur le justificatif de domicile pour affecter le dossier à l'agence géographique correspondante. Le dossier est ensuite assigné à un agent KYC en fonction de sa charge de travail, dans une limite de sécurité comprise entre 2 et 10 dossiers actifs.": "Le parcours interne débute à la soumission du dossier. Le back office présente les pièces, les champs extraits, les scores disponibles, les anomalies et les actions possibles. L'objectif est de permettre à l'agent KYC/chargé de clientèle de décider rapidement, tout en conservant les éléments nécessaires à la justification de la décision.",
        "La fluidité de ces parcours dépend directement de la qualité des données collectées et des mécanismes mis en œuvre pour en garantir l'intégrité absolue lors des échanges entre le client et la banque.": "La fluidité de ces parcours dépend directement de la qualité des données collectées et des mécanismes mis en œuvre pour en préserver l'intégrité.",
        "Le pipeline traite plusieurs données hautement sensibles. Pour chaque utilisateur, il collecte : (1) l'identité déclarative civile ; (2) les photos haute-résolution de la CNI recto/verso ; (3) la capture du selfie biométrique avec vidéo de liveness active ; (4) la facture ENEO ou CAMWATER comme preuve de domicile ; (5) l'attestation NIU fiscale ; (6) les consentements Loi n° 2024/017 ; (7) la signature sur écran tactile et les adresses IP avec horodatage pour l'audit trail.": "Le pipeline traite plusieurs catégories de données sensibles : identité déclarative, images de CNI recto verso, selfie ou preuve de vie, justificatif d'adresse selon le parcours retenu, informations relatives au NIU, consentements, signature, adresses IP et horodatages. Ces données doivent être reliées au bon dossier et conservées avec des traces exploitables.",
        "La qualité des données est validée à la source. Côté client, la PWA réalise des pré-contrôles d'image locaux (détection de flou, de reflets, centrage des documents) pour refuser les captures de mauvaise qualité avant l'envoi au serveur. Côté serveur, un calcul d'empreinte cryptographique SHA-256 est appliqué systématiquement lors de l'upload de chaque pièce originale pour en garantir l'intégrité absolue et prévenir toute altération ou corruption de fichier lors des transferts ou de la persistance au repos.": "La qualité des données doit être vérifiée le plus tôt possible. Côté client, les consignes de capture et les contrôles visuels réduisent les images floues, mal cadrées ou partiellement lisibles. Côté serveur, le calcul d'une empreinte SHA-256 lors de l'upload permet de contrôler l'intégrité des pièces et de relier chaque fichier à son dossier.",
        "Ces critères de qualité stricts nous obligent à fonder nos choix technologiques sur un état de l'art scientifique rigoureux de l'intelligence artificielle appliquée à la vérification d'identité et à l'extraction d'informations.": "Ces critères de qualité imposent d'appuyer les choix techniques sur l'état de l'art de l'extraction documentaire et de la vérification biométrique.",
        "Le développement d'un pipeline KYC souverain impose de s'appuyer sur la littérature scientifique de l'intelligence artificielle appliquée à la vérification d'identité. Concernant l'extraction textuelle des Cartes Nationales d'Identité (CNI) camerounaises, les techniques classiques d'OCR butent fréquemment sur l'usure des documents plastifiés, les polices variables et le bruit visuel des fonds complexes. Les travaux de Nguyen, Nguyen et Nguyen (2020) et de Raj, Sreenivas et Jawahar (2020) démontrent que l'extraction documentaire gagne en robustesse lorsque le pipeline combine une détection de structure de document (template layout) et une reconnaissance textuelle localisée. Dans VeriPass, cette approche est matérialisée par un moteur hybride : PaddleOCR (PP-OCRv5) est utilisé comme moteur ultra-rapide et local pour les champs structurés de la CNI, tandis qu'un modèle GLM-OCR (0.9B paramètres) prend le relais en asynchrone (Celery) pour l'extraction sémantique complexe et non structurée des factures d'électricité (ENEO) et d'eau (CAMWATER).": "Le développement d'un pipeline KYC impose de s'appuyer sur la littérature relative à l'extraction documentaire. Les CNI photographiées depuis un téléphone présentent des difficultés connues : usure du support, reflets, compression, cadrage imparfait, fonds complexes et variation des polices. Les travaux de Nguyen, Nguyen et Nguyen (2020) ainsi que ceux de Raj, Sreenivas et Jawahar (2020) montrent que l'extraction documentaire gagne en robustesse lorsque le pipeline combine localisation des zones utiles et reconnaissance textuelle. Dans VeriPass, cette logique justifie l'usage d'un moteur OCR rapide pour les cas simples, avec un traitement asynchrone plus poussé lorsque la capture est difficile ou incomplète.",
        "Pour la vérification d'identité faciale, la simple reconnaissance de visage ne suffit pas en raison des risques élevés d'attaques par présentation (usurpation par photo, vidéo ou masque). Yu et al. (2020) présentent une revue exhaustive des techniques de Face Anti-Spoofing, soulignant l'importance de coupler la reconnaissance faciale (Face Matching) avec des tests actifs de vivacité (Liveness Detection). VeriPass met en œuvre cette recommandation scientifique en obligeant le client à accomplir un challenge de mouvements aléatoires guidés par l'interface (clignements, inclinaison de la tête), analysé en temps réel par un modèle de détection de landmarks (MediaPipe) et de vivacité (MiniFASNet), puis compare le visage du selfie avec celui de la photo CNI via DeepFace avec un seuil de similarité strict fixé à 98.5%.": "Pour la vérification d'identité faciale, la reconnaissance du visage ne suffit pas. Les attaques par présentation, notamment photo, vidéo ou masque, obligent à combiner comparaison faciale et détection de vivacité. Yu et al. (2020) soulignent l'intérêt de coupler le face matching avec des tests de liveness. Dans VeriPass, cette orientation se traduit par un challenge actif guidé par l'interface, puis par une comparaison entre le selfie et la photo de la CNI. Les résultats doivent rester exprimés en scores, seuils et motifs afin de permettre une revue humaine en cas d'incertitude.",
        "Enfin, les standards d'identité numérique du GAFI (Financial Action Task Force, 2020) recommandent d'adopter une approche fondée sur les risques, garantissant la fiabilité et le maintien d'une supervision humaine. De même, les lignes directrices du CGAP (2021) sur l'inclusion financière rappellent que la transition digitale ne doit pas exclure les populations moins familiarisées avec la technologie. VeriPass intègre ce principe d'inclusion en proposant un guidage visuel très illustré et une gestion explicite des cas d'échecs (Plan B) permettant la reprise de capture simple ou l'escalade vers une revue manuelle assistée par un agent, prévenant ainsi tout blocage frustrant ou rejet injustifié.": "Enfin, les standards d'identité numérique du GAFI recommandent une approche fondée sur les risques, avec fiabilité, gouvernance et supervision humaine (Financial Action Task Force, 2020). Les travaux du CGAP rappellent aussi que la digitalisation financière doit éviter d'exclure les publics moins familiers avec les outils numériques (CGAP, 2021). Pour VeriPass, cela implique des consignes de capture simples, des reprises contrôlées et une escalade humaine lorsque l'automatisation ne suffit pas.",
        "Ces fondements scientifiques se traduisent techniquement par des exigences fonctionnelles et non fonctionnelles précises qui cadrent l'ensemble de notre développement logiciel.": "Ces éléments orientent les exigences fonctionnelles et non fonctionnelles du projet.",
        "Les exigences fonctionnelles (FR1 à FR19) cadrent précisément les flux applicatifs du système : authentification OTP, capture guidée, liveness challenge, validation locale du format de Numéro d'Identifiant Unique (NIU) via regex (^[A-Z][0-9]{12}[A-Z]$) et clé de contrôle algorithmique Modulo 23/26, consentement Loi n° 2024/017, signature tactile, file de validation assistée par agent KYC, et activation du dossier. Pour la conformité de modélisation, le pipeline intègre un simulateur d'Identifiant Bancaire Unique (IBU) basé sur la norme ISO 17442 (CM + segment BICEC 00001 + identifiant unique + clé de contrôle calculée selon l'algorithme Modulo 97-10 : Cle = 98 : (Number % 97)), permettant un développement et un test réalistes des interfaces. De plus, un mécanisme de sécurité robuste bloque l'accès (status LOCKED_LIVENESS) après 3 échecs consécutifs au liveness challenge pour éviter les attaques de présentation par brute force.": "Les exigences fonctionnelles cadrent les flux applicatifs du système : authentification, capture guidée, preuve de vie, confirmation des champs OCR, collecte de l'adresse, gestion du NIU, consentement, signature, soumission du dossier et revue back office. Elles prévoient aussi les cas dégradés : échec de capture, document illisible, OCR incertain, liveness non concluant, demande de complément et décision motivée.",
        "Les exigences non fonctionnelles (NFR11 à NFR16 selon la normalisation de conduite de projet) imposent des critères de performance et de volume stricts. L'inférence locale de l'IA (OCR et biométrie) doit s'exécuter en moins de 15 secondes pour garantir un parcours total fluide. Pour valider scientifiquement ces moteurs, le projet s'appuie sur la constitution progressive d'un dataset d'entraînement local anonymisé (conformément aux principes de minimisation de la Loi n° 2024/017) : un jeu de données de 5 000 spécimens de CNI camerounaises pour le fine-tuning de PaddleOCR (NFR11), et un jeu de test de 300 à 500 paires de visages pour l'évaluation de la similarité DeepFace (NFR12, FAR < 2%). La sécurité au repos impose le chiffrement AES-256 de tous les fichiers originaux sur le volume de stockage Docker centralisé.": "Les exigences non fonctionnelles portent sur la sécurité, la performance, l'auditabilité, la maintenabilité et l'expérience utilisateur. Les traitements OCR et biométriques doivent rester compatibles avec un parcours fluide. Les pièces et métadonnées doivent être protégées, les accès limités par rôle, les décisions tracées et les erreurs rendues compréhensibles pour le client comme pour les agents.",
        "La mise en œuvre coordonnée de ces exigences fonctionnelles et non fonctionnelles impose une méthodologie de conduite de projet particulièrement robuste pour suivre l'avancement et garantir la conformité réglementaire.": "La mise en œuvre de ces exigences impose une méthodologie capable de suivre l'avancement tout en conservant la traçabilité réglementaire.",
        "La conduite du projet d'ingénierie s'appuie sur une méthodologie hybride rigoureuse. Afin de garantir le respect des exigences réglementaires denses de la COBAC, la phase de spécification et d'analyse suit les principes structurés du Cycle en V : chaque exigence légale ou de conformité est directement mappée à un scénario de test d'acceptation et à un résultat vérifiable, assurant la traçabilité. Pour la réalisation logicielle, l'équipe adopte la démarche itérative Agile/Scrum. Le projet est découpé en sprints de deux semaines, rythmés par des réunions de planification, des revues régulières et la tenue d'un product backlog prioritaire.": "La conduite du projet s'appuie sur une méthodologie mixte. La phase de spécification et de validation s'inspire du cycle en V : chaque exigence importante doit pouvoir être reliée à une vérification. La réalisation logicielle suit une démarche incrémentale inspirée d'Agile/Scrum, avec des lots courts, des revues régulières et une priorisation des tâches selon le risque métier et technique.",
        "Cette agilité garantit une rapidité de développement et permet d'intégrer les retours continus des encadreurs de la BICEC. Les livrables techniques (contrats API FastAPI, modèles relationnels PostgreSQL, PWA React/Vite, back office, logs de sécurité, proofs d'exécution) sont produits par petits incréments testés localement sous le budget de ressources matérielles contraint (RAM de la machine hôte limitée à 16 Go, WSL 2 plafonné à 8 Go de RAM), assurant la résilience et la viabilité de la solution avant sa démonstration finale.": "Cette approche permet d'intégrer les retours d'encadrement sans perdre la maîtrise des exigences. Les livrables techniques (contrats API FastAPI, modèles relationnels PostgreSQL, PWA React/Vite, back office, journaux de sécurité et preuves d'exécution) sont produits par incréments, testés localement et documentés afin de préparer la démonstration finale.",
        "Ce cadre méthodologique s'incarne dans un calendrier de réalisation précis, structuré autour de jalons mensuels (de M1 à M5) et d'une gestion proactive des risques techniques et opérationnels. Les risques du projet sont activement suivis dans une matrice d'atténuation. La collaboration étroite avec M. Jackson KOMBE LELE et les équipes techniques du Core Banking et de la Sécurité IT permet de valider les compromis de conception au fur et à mesure.": "Ce cadre méthodologique s'incarne dans un calendrier structuré par jalons. Les risques suivis concernent principalement la qualité des images, les performances OCR, la robustesse biométrique, la sécurité des pièces et la validation métier des parcours. Les échanges avec M. Jackson KOMBE LELE et les équipes concernées permettent d'ajuster les compromis de conception au fur et à mesure.",
        "La confrontation avec ces réalités industrielles complexes a constitué le socle de notre développement professionnel et personnel, renforçant nos compétences d'ingénieur.": "Ces choix de cadrage conduisent à une synthèse des acquis techniques, méthodologiques et professionnels du chapitre.",
        "2.10 Bilan des Acquis d'Apprentissage et Apports Professionnels": "2.10 Synthèse du chapitre",
        "Ce projet d'ingénierie de fin d'études a constitué un puissant vecteur de développement professionnel et personnel. Sur le plan technique, il a permis de maîtriser les architectures de développement cloud-native on-premise, d'intégrer des modules d'apprentissage profond locaux (PaddleOCR, DeepFace, MiniFASNet) sous des contraintes matérielles réelles de production bancaire, et de concevoir des mécanismes de résilience complexes (IndexedDB, Service Workers, progressive upload asynchrone) pour adapter le logiciel aux contraintes d'infrastructure camerounaises (le délestage).": "Ce chapitre a transformé le cadre réglementaire et métier en exigences de conception. Il a précisé les acteurs, les parcours, les données sensibles, les critères de qualité, les contraintes de sécurité et les références techniques utiles à la solution. Il montre que la valeur de VeriPass ne repose pas seulement sur l'OCR ou la biométrie, mais sur leur intégration dans un processus contrôlable.",
        "Sur le plan méthodologique et humain, ce stage au sein de la BICEC a développé une solide culture de la conformité, de la rigueur bancaire et de la sécurité dès la conception (Security by Design). Les interactions quotidiennes avec les développeurs et les juristes conformité de la banque ont renforcé nos capacités de communication professionnelle, d'autonomie et de gestion des risques. Ce travail démontre qu'un ingénieur de fin d'études doit savoir concilier performance algorithmique, rentabilité économique et conformité réglementaire pour livrer un produit créateur de valeur pour l'entreprise.": "Le chapitre suivant peut donc aborder l'architecture avec un cadre clair : quelles données entrent dans le pipeline, quels traitements les transforment, quels états doivent être conservés, quels contrôles sont automatisés et quels points de décision restent confiés aux acteurs habilités.",
    }

    missing = []
    for old, new in replacements.items():
        if not replace_paragraph(doc, old, new):
            missing.append(old[:90])

    targeted = {
        "Le problème à résoudre n'est pas uniquement logiciel": "Le problème à résoudre n'est pas uniquement logiciel. Il se situe à l'intersection de l'expérience client, de la qualité des données, de la sécurité applicative et de la conformité COBAC. La problématique centrale de ce mémoire peut donc s'énoncer ainsi : comment digitaliser l'onboarding client de la BICEC au moyen d'un pipeline de vérification KYC, afin de réduire les délais et les erreurs de constitution de dossier, tout en conservant la validation humaine, la conservation des preuves, la sécurité des données et la traçabilité exigées par le cadre bancaire ?",
        "Cette problématique se décline en cinq questions opérationnelles": "Cette problématique se décline en cinq questions opérationnelles : comment guider la capture de CNI depuis un navigateur mobile ; comment extraire les champs utiles malgré le flou, les reflets ou le mauvais cadrage ; comment vérifier la vivacité et la cohérence du visage sans rendre le parcours excessivement lourd ; comment structurer une base et des journaux auditables ; comment organiser la revue humaine des dossiers sans perdre la traçabilité des décisions ?",
        "Pour apporter des réponses concrètes et structurées": "Pour répondre à ces questions, le projet propose BICEC VeriPass, un écosystème d'acquisition client articulant une application mobile, une API, des traitements OCR et biométriques, une base de données relationnelle, un stockage documentaire et un back office de revue.",
        "BICEC VeriPass est conçu comme un pipeline robuste": "BICEC VeriPass est conçu comme un pipeline d'acquisition client et de gestion de preuves numériques. La solution se compose d'une interface client PWA, d'un back office de validation, d'une API FastAPI, de workers Celery/Redis pour les traitements asynchrones, d'une base PostgreSQL et d'un stockage documentaire local.",
        "Le principe directeur est celui de l'automatisation contrôlée": "Le principe directeur est celui de l'automatisation contrôlée : les moteurs OCR et biométriques préparent le dossier, calculent des scores et signalent les anomalies, mais l'agent habilité conserve la responsabilité de la validation finale. VeriPass agit donc comme un outil d'aide à l'instruction KYC, sans intégrer directement les bases transactionnelles de production.",
        "Au-delà de la performance purement logicielle": "Au-delà de l'architecture logicielle, la pertinence de VeriPass doit aussi être appréciée sous l'angle économique et opérationnel.",
        "Une contribution majeure de ce travail d'ingénierie réside": "L'analyse économique de la solution repose sur un principe simple : une partie des coûts du processus papier provient des impressions, de l'archivage physique, des reprises de saisie et des relances liées aux dossiers incomplets. La digitalisation peut réduire ces coûts si elle diminue les reprises, améliore la complétude des dossiers et facilite la revue interne.",
        "Le budget matériel pour le serveur de production": "Le prototype privilégie une infrastructure locale et reproductible, fondée sur Docker, PostgreSQL, Redis, Celery et des briques open source. Ce choix limite la dépendance à des services SaaS pour les données sensibles et facilite les démonstrations techniques. Une mise en production demanderait toutefois un dimensionnement formel, une revue de sécurité et une validation d'exploitation.",
        "L'impact sur le compte de résultat est immédiat": "L'impact économique attendu doit donc être formulé avec prudence. VeriPass peut contribuer à réduire le coût d'acquisition client si le parcours diminue les allers retours, accélère la revue des dossiers et réduit les erreurs de saisie. Ces gains devront être mesurés pendant une phase pilote avant toute conclusion chiffrée.",
        "L'objectif premier de la plateforme VeriPass": "L'objectif premier de VeriPass est de réduire le temps et l'effort de constitution d'un dossier KYC, sans affaiblir les contrôles réglementaires. Le système doit guider l'utilisateur pas à pas, collecter les pièces utiles, permettre la vérification des champs extraits, réaliser une preuve de vie, recueillir le consentement et transmettre au back office un dossier structuré, traçable et exploitable.",
        "Cette agilité garantit une rapidité de développement": "Cette approche permet d'intégrer les retours d'encadrement sans perdre la maîtrise des exigences. Les livrables techniques (contrats API FastAPI, modèles relationnels PostgreSQL, PWA React/Vite, back office, journaux de sécurité et preuves d'exécution) sont produits par incréments, testés localement et documentés afin de préparer la démonstration finale.",
        "Ce premier chapitre pose les bases contextuelles": "Ce premier chapitre pose les bases contextuelles, réglementaires, opérationnelles et économiques du projet. Il présente la BICEC et le cadre du stage, puis analyse la pression concurrentielle exercée par les services financiers digitaux sur les parcours traditionnels d'acquisition client. Il met ensuite en relation les exigences du règlement COBAC R 2023/01, les contraintes de protection des données et les limites du processus manuel d'entrée en relation. Cette analyse permet de formuler la problématique d'ingénierie à laquelle répond BICEC VeriPass.",
        "La Banque Internationale du Cameroun pour l'Épargne": "La Banque Internationale du Cameroun pour l'Épargne et le Crédit, plus connue sous le sigle BICEC, est une institution financière commerciale opérant au Cameroun. La présentation institutionnelle de la banque la situe comme filiale du Groupe Banque Centrale Populaire et comme acteur de référence du paysage bancaire camerounais (BICEC, 2026). Le site institutionnel mentionne notamment un réseau de 40 agences, 2 centres d'affaires et un espace PME. La fiche de validation du sujet de stage retient, pour le périmètre de ce mémoire, un effectif d'environ 600 collaborateurs.",
        "Le stage de fin d'études d'ingénieur": "Le stage de fin d'études d'ingénieur s'est déroulé au sein du Département Étude et Développement à Douala, sous l'encadrement industriel de M. Jackson Parfait KOMBE LELE. La mission confiée portait sur la conception et le développement de BICEC VeriPass, un écosystème d'acquisition client destiné à digitaliser le parcours KYC et à structurer les contrôles documentaires et biométriques. La période de stage indiquée sur la fiche de validation s'étend du 19 janvier 2026 au 18 juin 2026.",
        "Cette assise territoriale solide": "Cette présence territoriale impose à la BICEC de concilier proximité bancaire et modernisation progressive de l'expérience client.",
        "L'ouverture de compte est le point de contact": "L'ouverture de compte est un point de contact décisif dans la relation client. Dans un marché camerounais marqué par l'usage courant du Mobile Money et par la diffusion des services financiers digitaux, les clients comparent de plus en plus l'expérience bancaire aux parcours mobiles simples et disponibles à distance. Face à ces usages, un parcours d'ouverture de compte centré sur l'agence, le papier et les allers retours administratifs perd en attractivité.",
        "Les documents de cadrage du projet identifient": "Les documents de cadrage du projet retiennent un délai d'ouverture pouvant aller de 48 heures à 14 jours dans le processus manuel de la BICEC. Ce délai dépend de la disponibilité du client, de la complétude du dossier, de la lisibilité des pièces et des échanges nécessaires entre agence et back office. Cette friction justifie l'objectif de réduire le temps de constitution du dossier, tout en conservant une revue interne conforme.",
        "Or, cette exigence d'agilité commerciale": "Cette exigence de rapidité doit toutefois rester compatible avec le cadre réglementaire applicable dans la zone CEMAC.",
        "Le règlement COBAC R-2023/01": "Le règlement COBAC R 2023/01 du 19 décembre 2023 relatif aux diligences des établissements assujettis en matière de lutte contre le blanchiment des capitaux et le financement du terrorisme constitue le cadre juridique de référence du projet dans la zone CEMAC. Il impose aux établissements assujettis d'identifier leurs clients, de vérifier leur identité à partir de sources fiables, de tenir compte du risque et de conserver les éléments utiles à la vigilance. Cette obligation exclut une lecture purement commerciale du KYC et impose de maintenir une décision humaine explicable.",
        "En parallèle, la Loi n° 2024/017": "En parallèle, la Loi n° 2024/017 relative à la protection des données à caractère personnel au Cameroun renforce l'attention portée au consentement, à la minimisation, à la sécurité et à la maîtrise des données sensibles. Pour VeriPass, cette contrainte invite à privilégier une architecture où les pièces d'identité, les données biométriques et les journaux restent sous contrôle de l'organisation.",
        "L'obligation légale d'héberger localement": "Ces exigences réglementaires mettent en évidence les limites d'un processus manuel difficile à tracer et à auditer.",
        "Le processus manuel actuel de la BICEC présente": "Le processus manuel d'entrée en relation présente plusieurs limites opérationnelles. Le client doit se déplacer, fournir des photocopies et compléter des formulaires. Les agents doivent ensuite ressaisir une partie des informations, vérifier la complétude du dossier et traiter les éventuelles pièces illisibles. Ces étapes augmentent le délai de traitement et multiplient les risques d'erreur.",
        "La quatrième limite réside": "Une autre limite concerne la traçabilité. Dans un processus papier, les corrections, relances et arbitrages sont plus difficiles à reconstituer qu'avec un dossier numérique horodaté. L'automatisation du traitement documentaire et de l'extraction des données peut donc réduire certaines tâches répétitives, à condition de conserver une validation humaine et des preuves auditables.",
        "Afin de surmonter ces contraintes opérationnelles": "À partir de ces constats, le mémoire formule une problématique d'ingénierie centrée sur la digitalisation contrôlée du KYC.",
        "Ce premier chapitre a établi la problématique réglementaire": "Ce premier chapitre a établi la problématique réglementaire, commerciale, technique et économique de VeriPass. La solution doit réduire la friction de l'ouverture de compte tout en respectant les exigences de la zone CEMAC. L'architecture proposée répond à cette contrainte par un pipeline numérique structuré, auditable et compatible avec une validation humaine. Le chapitre suivant formalise le besoin, les données d'identité, les exigences fonctionnelles et non fonctionnelles, puis le cadrage méthodologique du projet.",
    }
    for needle, new in targeted.items():
        if not replace_containing(doc, needle, new):
            missing.append(f"needle:{needle[:70]}")

    replace_inside(doc, "human in the loop", "validation humaine dans la boucle")
    replace_inside(doc, "Human-in-the-Loop", "validation humaine dans la boucle")
    replace_inside(doc, "mobile-first", "orienté mobile")
    replace_inside(doc, "hors-ligne", "hors ligne")
    replace_inside(doc, "multi-rôles", "à rôles multiples")
    replace_inside(doc, "load-balancing", "équilibrage de charge")
    replace_inside(doc, "deep-linking", "liens applicatifs")
    replace_inside(doc, "Tableau 5. Rentabilité économique et impacts financiers directs", "Tableau 5. Impacts économiques attendus et points de vigilance")
    replace_inside(doc, "30% à 40% de dossiers comportant des fautes", "Dossiers incomplets ou comportant des erreurs de saisie")
    replace_inside(doc, "Face Matching DeepFace (seuil 98.5%) et liveness de vivacité", "Comparaison faciale et preuve de vie avec seuils à calibrer")
    replace_inside(doc, "Moins de 15 minutes (cible : 11 min), backlog réduit de 80%", "Réduction attendue du temps de constitution et de revue, à mesurer en pilote")
    replace_inside(doc, "Accès à sa session active, aux démos et SSO Bi-Cresco", "Accès à sa session active et au suivi du dossier")
    replace_inside(doc, "Dataset de 5 000 CNI anonymisées (NFR11 : ground truth)", "Jeux de tests anonymisés à constituer et documenter")
    replace_inside(doc, "Reconnaissance faciale à 98.5% (NFR12 : FAR < 2%)", "Seuils de reconnaissance faciale à calibrer avant production")
    replace_inside(doc, "backoffice", "back office")
    replace_inside(doc, "back-office", "back office")
    replace_inside(doc, "Backoffice", "Back office")

    scan(doc)
    doc.save(DST)
    print(DST)
    if missing:
        print("Missing exact matches:")
        for item in missing:
            print(item)


if __name__ == "__main__":
    main()
