import type { StepMeta, ApplicationData, OCRField } from './types';

export const STEP_SEQUENCE: StepMeta[] = [
  { id: 'welcome', label: 'Welcome', group: 'Entry', icon: 'Sparkles' },
  { id: 'language', label: 'Language', group: 'Entry', icon: 'Globe' },
  { id: 'phone-otp', label: 'Phone + OTP', group: 'Auth', icon: 'Smartphone' },
  { id: 'email-verify', label: 'Email Verify', group: 'Auth', icon: 'Mail' },
  { id: 'pin-setup', label: 'PIN Setup', group: 'Auth', icon: 'Lock' },
  { id: 'biometrics', label: 'Biometrics', group: 'Auth', icon: 'Fingerprint' },
  { id: 'id-front', label: 'ID Front', group: 'Identity', icon: 'CreditCard' },
  { id: 'id-back', label: 'ID Back', group: 'Identity', icon: 'CreditCard' },
  { id: 'ocr-review', label: 'OCR Review', group: 'Identity', icon: 'ScanLine' },
  { id: 'liveness', label: 'Liveness Check', group: 'Identity', icon: 'Camera' },
  { id: 'address', label: 'Address', group: 'Address', icon: 'MapPin' },
  { id: 'address-proof', label: 'Proof Upload', group: 'Address', icon: 'FileCheck' },
  { id: 'fiscal-id', label: 'Fiscal / Tax ID', group: 'Address', icon: 'FileText' },
  { id: 'consent', label: 'Consent', group: 'Consent', icon: 'ShieldCheck' },
  { id: 'signature', label: 'Signature', group: 'Consent', icon: 'PenTool' },
  { id: 'review-summary', label: 'Review & Submit', group: 'Submit', icon: 'CheckCircle' },
  { id: 'uploading', label: 'Uploading', group: 'Submit', icon: 'Upload' },
  { id: 'success', label: 'Success!', group: 'Submit', icon: 'PartyPopper' },
];

export const MOCK_OCR_FIELDS: OCRField[] = [
  { key: 'fullName', label: 'Full Name', value: 'María García López', confidence: 97, edited: false },
  { key: 'nationalId', label: 'National ID', value: 'INE-1234567890', confidence: 94, edited: false },
  { key: 'dateOfBirth', label: 'Date of Birth', value: '15/03/1990', confidence: 88, edited: false },
  { key: 'address', label: 'Address', value: 'Av. Reforma 222, Col. Juárez', confidence: 72, edited: false },
  { key: 'issuedDate', label: 'Issue Date', value: '01/06/2021', confidence: 91, edited: false },
  { key: 'expiryDate', label: 'Expiry Date', value: '01/06/2031', confidence: 85, edited: false },
];

export const MOCK_APPLICATIONS: ApplicationData[] = [
  {
    id: 'APP-2024-0001',
    fullName: 'María García López',
    phone: '+52 55 1234 5678',
    email: 'maria.garcia@email.com',
    nationalId: 'INE-1234567890',
    dateOfBirth: '15/03/1990',
    address: 'Av. Reforma 222, Col. Juárez',
    city: 'Ciudad de México',
    state: 'CDMX',
    fiscalId: 'GALM900315HDF',
    status: 'pending',
    submittedAt: '2024-01-15T14:32:00Z',
    ocrFields: MOCK_OCR_FIELDS,
    livenessScore: 96,
    idFrontUrl: '',
    idBackUrl: '',
    selfieUrl: '',
    proofUrl: '',
    signatureUrl: '',
  },
  {
    id: 'APP-2024-0002',
    fullName: 'Carlos Hernández Ruiz',
    phone: '+52 33 9876 5432',
    email: 'carlos.hr@email.com',
    nationalId: 'INE-0987654321',
    dateOfBirth: '22/07/1985',
    address: 'Calle Hidalgo 45, Centro',
    city: 'Guadalajara',
    state: 'Jalisco',
    fiscalId: 'HERC850722MJC',
    status: 'pending',
    submittedAt: '2024-01-15T15:10:00Z',
    ocrFields: [
      { key: 'fullName', label: 'Full Name', value: 'Carlos Hernández Ruiz', confidence: 99, edited: false },
      { key: 'nationalId', label: 'National ID', value: 'INE-0987654321', confidence: 96, edited: false },
      { key: 'dateOfBirth', label: 'Date of Birth', value: '22/07/1985', confidence: 92, edited: false },
      { key: 'address', label: 'Address', value: 'Calle Hidalgo 45, Centro', confidence: 68, edited: false },
      { key: 'issuedDate', label: 'Issue Date', value: '15/02/2020', confidence: 94, edited: false },
      { key: 'expiryDate', label: 'Expiry Date', value: '15/02/2030', confidence: 90, edited: false },
    ],
    livenessScore: 91,
    idFrontUrl: '',
    idBackUrl: '',
    selfieUrl: '',
    proofUrl: '',
    signatureUrl: '',
  },
  {
    id: 'APP-2024-0003',
    fullName: 'Ana Sofía Martínez',
    phone: '+52 81 5555 1234',
    email: 'ana.sofia@email.com',
    nationalId: 'INE-1122334455',
    dateOfBirth: '08/11/1995',
    address: 'Blvd. Constitución 789',
    city: 'Monterrey',
    state: 'Nuevo León',
    fiscalId: '',
    status: 'limited',
    submittedAt: '2024-01-14T09:22:00Z',
    ocrFields: [
      { key: 'fullName', label: 'Full Name', value: 'Ana Sofía Martínez', confidence: 95, edited: false },
      { key: 'nationalId', label: 'National ID', value: 'INE-1122334455', confidence: 89, edited: false },
      { key: 'dateOfBirth', label: 'Date of Birth', value: '08/11/1995', confidence: 93, edited: false },
      { key: 'address', label: 'Address', value: 'Blvd. Constitución 789', confidence: 81, edited: false },
      { key: 'issuedDate', label: 'Issue Date', value: '20/09/2022', confidence: 97, edited: false },
      { key: 'expiryDate', label: 'Expiry Date', value: '20/09/2032', confidence: 95, edited: false },
    ],
    livenessScore: 88,
    idFrontUrl: '',
    idBackUrl: '',
    selfieUrl: '',
    proofUrl: '',
    signatureUrl: '',
  },
  {
    id: 'APP-2024-0004',
    fullName: 'Roberto Díaz Flores',
    phone: '+52 222 333 4444',
    email: 'roberto.df@email.com',
    nationalId: 'INE-5566778899',
    dateOfBirth: '30/01/1988',
    address: 'Calle 5 de Mayo 123',
    city: 'Puebla',
    state: 'Puebla',
    fiscalId: 'DIFR880130HPB',
    status: 'approved',
    submittedAt: '2024-01-13T11:45:00Z',
    ocrFields: [
      { key: 'fullName', label: 'Full Name', value: 'Roberto Díaz Flores', confidence: 98, edited: false },
      { key: 'nationalId', label: 'National ID', value: 'INE-5566778899', confidence: 97, edited: false },
      { key: 'dateOfBirth', label: 'Date of Birth', value: '30/01/1988', confidence: 96, edited: false },
      { key: 'address', label: 'Address', value: 'Calle 5 de Mayo 123', confidence: 90, edited: false },
      { key: 'issuedDate', label: 'Issue Date', value: '10/03/2019', confidence: 95, edited: false },
      { key: 'expiryDate', label: 'Expiry Date', value: '10/03/2029', confidence: 93, edited: false },
    ],
    livenessScore: 99,
    idFrontUrl: '',
    idBackUrl: '',
    selfieUrl: '',
    proofUrl: '',
    signatureUrl: '',
  },
  {
    id: 'APP-2024-0005',
    fullName: 'Lucía Fernández Torres',
    phone: '+52 999 888 7777',
    email: 'lucia.ft@email.com',
    nationalId: 'INE-6677889900',
    dateOfBirth: '12/05/1992',
    address: 'Calle 60 #456, Centro',
    city: 'Mérida',
    state: 'Yucatán',
    fiscalId: 'FETL920512MYU',
    status: 'rejected',
    submittedAt: '2024-01-12T16:20:00Z',
    ocrFields: [
      { key: 'fullName', label: 'Full Name', value: 'Lucía Fernández Torres', confidence: 45, edited: false },
      { key: 'nationalId', label: 'National ID', value: 'INE-667788??00', confidence: 52, edited: false },
      { key: 'dateOfBirth', label: 'Date of Birth', value: '12/05/19??', confidence: 38, edited: false },
      { key: 'address', label: 'Address', value: 'Calle 60 #456', confidence: 55, edited: false },
      { key: 'issuedDate', label: 'Issue Date', value: '??/??/2018', confidence: 30, edited: false },
      { key: 'expiryDate', label: 'Expiry Date', value: '??/??/2028', confidence: 28, edited: false },
    ],
    livenessScore: 42,
    idFrontUrl: '',
    idBackUrl: '',
    selfieUrl: '',
    proofUrl: '',
    signatureUrl: '',
    rejectionReason: 'ID document severely damaged — unable to verify identity. Liveness check failed with low confidence score.',
  },
];

export const LANGUAGES = [
  { code: 'es', label: 'Español', flag: '🇲🇽' },
  { code: 'en', label: 'English', flag: '🇺🇸' },
  { code: 'pt', label: 'Português', flag: '🇧🇷' },
  { code: 'fr', label: 'Français', flag: '🇫🇷' },
];

export const STATES = [
  'Aguascalientes', 'Baja California', 'CDMX', 'Chiapas', 'Chihuahua',
  'Coahuila', 'Colima', 'Durango', 'Guanajuato', 'Guerrero',
  'Hidalgo', 'Jalisco', 'Estado de México', 'Michoacán', 'Morelos',
  'Nayarit', 'Nuevo León', 'Oaxaca', 'Puebla', 'Querétaro',
  'Quintana Roo', 'San Luis Potosí', 'Sinaloa', 'Sonora', 'Tabasco',
  'Tamaulipas', 'Tlaxcala', 'Veracruz', 'Yucatán', 'Zacatecas',
];
